### ISSUE TITLE
Hey guys I think that suppose to be lastirreversibleblock?

### ISSUE THREAD

**Issue by tngflx** [busyorg/busy-api#11]
https://github.com/busyorg/busy-api/blob/34a4a96246d4258aa689d0d295d735544c28a583/server.js#L297

Its searching on old block instead of new block. If res is null, then it should start with the latest irreversible block num. Why start with 2000000?

**Comment by Sekhmet** [comment]
Sorry for late reply.
It was used so it also processed old blocks (but right now it's too old). However, we can control it using redis.
